Решение задач модуля 1
js-tasks-ru/jsbasic-20230428_olabin pull request #2
Opened 2023-05-03 06:16 UTC by Olgabindasova

Все 5 задач

2023-05-03 06:17 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-03 13:58 UTC, SinimaWath requested changes

2023-05-03 13:58 UTC, SinimaWath commented on 1-module/1-task/index.js
> +    chislo = factorial(n);
Эта строчка кода никогда не исполняется, так как она после return -> не нужна

2023-05-03 13:58 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  else if(n > 1){
Тут есть лишние условия, которые стоит убрать:
```
if (n === 0 || n === 1) {
   return chislo;
}

for(i = n; i >= 1; i--){
  chislo = chislo * i;
}

return chislo;
```

2023-05-04 09:21 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-05-04 18:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-05-05 10:17 UTC, SinimaWath approved these changes

2023-05-05 10:18 UTC, merged